# define endpoint exposure for web access, set logging levels for specific packages, and configure the name of the Spring application
management:
  endpoint:
    web:
      exposure:
        include: info, refresh, keepalive, health
logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG

spring:
  application:
    name: minikube-sample
